<?php include (__DIR__.'/layout.phtml'); ?>

<form method="post" action="/register">
  <div class="container">
    <h1>Регистрация</h1>
    <hr>
    <label for="name"><b>Имя</b></label>
    <input type="text" placeholder="Name" name="name" required>

    <label for="psw"><b>Пароль</b></label>
    <input type="password" placeholder="Password" name="password" required>

    <button type="submit" class="registerbtn">Register</button>
  </div>
</form>